### PR TITLE
Adding required fields details for IGM specification

### PR DESCRIPTION
**Pull request by tarun-patel**

### CODE REVIEW

**Review by BLR-0118 — CHANGES_REQUESTED** [review]
Pls schedule a review of the use-cases, how they are enabled in the spec and API contract. Without this, no further PRs will be merged.

**Comment by BLR-0118** [comment]
1. gro_type.json - instead of interfacing & counterparty, why don't we use consistent terminology - complainant GRO, respondent GRO. Since this is gro type, when complaint is sent to the cascaded network, the respondent becomes the complainant and the "cascaded counterparty" becomes the respondent. Shouldn't 2 types be sufficient for complainant & respondent GRO?
2. same with issue_source_type.json, also instead of "End User", can we call it "Consumer" to be consistent with Beckn terminology?
3. issue_status.json - what's the difference between rejected & declined, closed & resolved?
4. provider_type.json - same as in 1.

**Comment by nitinmish** [comment]
In line please:

________________________________

**Comment by Rishabh-ondc** [comment]
1.  gro_type.json - instead of interfacing & counterparty, why don't we use consistent terminology - complainant GRO, respondent GRO. Since this is gro type, when complaint is sent to the cascaded network, the respondent becomes the complainant and the "cascaded counterparty" becomes the respondent. Shouldn't 2 types be sufficient for complainant & respondent GRO?

[Nitin] There can be multiple respondent for an issue, and both, cascaded and counterparty are required to respond with their respective GRO. We need to differentiate between principle, first agency and cascaded agencies which can also be multiple for posteriority I am suggesting to maintain at least 3 levels in order to ensure cascading is communicated to complainant App.

  2.  same with issue_source_type.json, also instead of "End User", can we call it "Consumer" to be consistent with Beckn terminology?
  [Rishabh] Separate enums for Buyer and Seller to be created.
  
  3.  issue_status.json - what's the difference between rejected & declined, closed & resolved?

 [Nitin] I Agree, we should only have Accepted, Acknowledged, Resolved and Closed. 
 Resolved is status set by respondent, Closing is at the hands of complainant.
  
  [Rishabh] 'Rejected' and 'Declined' enums to be removed.
  
  4.  provider_type.json - same as in 1.
  [Rishabh] Same as in 1

**Pull request merged**
